### ISSUE TITLE
Core/Formula Separation [Tracking Issue]

### ISSUE THREAD

**Issue by apjanke** [Homebrew/legacy-homebrew#50650]
This is a list of issues and commits related to the Homebrew [Core/Formula Separation (#49752)](https://github.com/Homebrew/homebrew/pull/49752). It's done as an issue instead of a label because it will have items from multiple repos and will include annotations.

## Relevant Repos

https://github.com/homebrew/homebrew - the original Homebrew repo
https://github.com/homebrew/homebrew-core - the new core formula tap
https://github.com/homebrew/brew - where the new `brew` package manager code will go in step 2

##  Posts and Announcements

* [Announcement on `homebrew-discuss`](https://groups.google.com/forum/#!topic/homebrew-discuss/D_weS6pZesg) (mailing list)
* [Announcement on Twitter](https://twitter.com/MacHomebrew/status/716614362711080960) – follow-ups: [#1](https://twitter.com/MacHomebrew/status/716614525517172736), [#2](https://twitter.com/MacHomebrew/status/716617201936105472)

##  Separation Work

* [x] Core/formula separation – #49752 (main discussion)
* [X] Core/Formula Separation Step 1 – #49904 
* [x]  Core/formula separation Part 2(a) – #50653 
* [x]  Core/formula separation Part 2(b) – Homebrew/brew#2 
* [X] doc: update for core/formula separation – #50632 
* [x] doc: more updates for core/formula separation – #50649 
* [X]  Update documentation after repository split. – Homebrew/brew#3 
* [X]  test-bot: handle legacy formulae PR from – #50635 
* [x] update .github templates in homebrew-core – Homebrew/homebrew-core#8
* [x] tap: support `--full` even if installed – #50639 
* [x] `GitHub.issues_matching` or other related methods need to be updated to search both tap repo and main repo. – Homebrew/brew#8
* [x] Check and update doco in remaining central taps for URLs etc
 * [x] [homebrew/dev-tools](https://github.com/Homebrew/homebrew-dev-tools) – Homebrew/homebrew-dev-tools#4
  * [x] homebrew/versions
  * [x] homebrew/dupes
  * [x] homebrew/science
  * [x] homebrew/games
  * [x] homebrew/php
  * [x] homebrew/python
  * [x] homebrew/boneyard – Homebrew/homebrew-boneyard#107
  * [x] homebrew/fuse
  * [x] homebrew/binary
  * [x] homebrew/services
  * [x] homebrew/nginx
  * [x] homebrew/x11
  * [x] homebrew/emacs
  * [x] homebrew/bundle – Homebrew/homebrew-bundle#166
  * [x] homebrew/devel-only
  * [x] homebrew/head-only
  * [x] homebrew/apache
  * [x] homebrew/gui

##  Resulting Issues

* [x]  test-bot failing with `brew doctor` errors and leftover kegs – #50651
* [x]  brew search: 422 Unprocessable Entity – Homebrew/brew#6 

## Other Issues

* [ ] `brew doctor` need to be updated to include both brew and homebrew-core repos origin check. At the same time, it may be a good idea to disable CoreTap auto-tap for `brew doctor`.
* [x] Homebrew/core Travis CI fails to test formula. https://github.com/Homebrew/brew/issues/100

**Comment by UniqMartin** [comment]
Seems like everything is done except for “`brew doctor` need to be updated to include new repo check.”, that I don't understand. Can you explain what needs to be done here?

**Comment by apjanke** [comment]
You know what; I heard that from @xu-cheng and I forgot exactly what it means. I think it just means to have `doctor` check that `origin` is pointing at the new repo.

I believe the [current `check_git_origin` check] (from d127569053d538fb17cc20313a8ae9094d53a7c9) now covers this, and we can tick it off and close this issue. Is that correct, Xu?

**Comment by xu-cheng** [comment]
Yeah, I'm thinking we should add git origin check for both `homebrew/brew` and `homebrew/core` tap.

Another thing is we probably should stop `hombrew/core` auto-tap during `brew doctor`. Because it could introduce nasty error if users happen to have not installed git.

**Comment by apjanke** [comment]
I think the git origin check for `homebrew/brew` [is already there](https://github.com/Homebrew/brew/blob/144d86f73315f59d65234ace69880bb9d3a90acb/Library/Homebrew/diagnostic.rb#L1088-L1099); we just need to add it for `homebrew/core` tap. (Sorry for broken link in my previous comment.)

Yeah. Maybe we should stop auto-tap of everything in `brew doctor`: besides the `git` error, as a diagnostic tool, I'd expect it to be "read-only".

**Comment by mikemcquaid** [comment]
> Another thing is we probably should stop hombrew/core auto-tap during brew doctor. Because it could introduce nasty error if users happen to have not installed git.

👍

**Comment by MikeMcQuaid** [comment]
This was done ✨
